### ISSUE TITLE
how to use it linear-algebra-js on the terminal?

### ISSUE THREAD

**Issue by r03ert0** [rohan-sawhney/linear-algebra-js#1]
Is it possible to use linear-algebra-js directly with `node` on the terminal, without a web browser?

**Comment by rohan-sawhney** [comment]
It is now! I've created separate node and web directories. Just require('PATH_TO/node/linear-algebra.js') in your source file. All classes in the framework can be accessed through that (see [test-node.js](https://github.com/rohan-sawhney/linear-algebra-js/blob/master/tests/test-node.js))

**Comment by r03ert0** [comment]
awesome! thank you!
